/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as appChatRouteImport } from './routes/(app)/chat'
import { Route as appChatChatIdRouteImport } from './routes/(app)/chat.$chatId'

const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const appChatRoute = appChatRouteImport.update({
  id: '/(app)/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const appChatChatIdRoute = appChatChatIdRouteImport.update({
  id: '/$chatId',
  path: '/$chatId',
  getParentRoute: () => appChatRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRoute
  '/chat': typeof appChatRouteWithChildren
  '/chat/$chatId': typeof appChatChatIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRoute
  '/chat': typeof appChatRouteWithChildren
  '/chat/$chatId': typeof appChatChatIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRoute
  '/(app)/chat': typeof appChatRouteWithChildren
  '/(app)/chat/$chatId': typeof appChatChatIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth' | '/chat' | '/chat/$chatId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/chat' | '/chat/$chatId'
  id: '__root__' | '/' | '/auth' | '/(app)/chat' | '/(app)/chat/$chatId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRoute
  appChatRoute: typeof appChatRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/chat': {
      id: '/(app)/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof appChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/chat/$chatId': {
      id: '/(app)/chat/$chatId'
      path: '/$chatId'
      fullPath: '/chat/$chatId'
      preLoaderRoute: typeof appChatChatIdRouteImport
      parentRoute: typeof appChatRoute
    }
  }
}

interface appChatRouteChildren {
  appChatChatIdRoute: typeof appChatChatIdRoute
}

const appChatRouteChildren: appChatRouteChildren = {
  appChatChatIdRoute: appChatChatIdRoute,
}

const appChatRouteWithChildren =
  appChatRoute._addFileChildren(appChatRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRoute,
  appChatRoute: appChatRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
